---
title: "EDA new data"
runtime: shiny
output: html_document
---

```{r message = F, warning  = F, echo = F}
library(tidyverse)
library(plotly)
library(shiny)

knitr::opts_chunk$set(echo=FALSE, 
               warning=FALSE, message=FALSE)
```

```{r}
my_theme <- theme_minimal() +
  theme(plot.title = element_text(hjust = .5))
theme_set(my_theme)
```

We present the new data below. \@Chad, you'll need to run `main/eda_new_data.py` first (to create the images). 

The below figure plots `Xcen` and `Ycen`, specifically doing `x = Ycen, y = -Xcen`. 

```{r message = F, warning  = F}
data_vis <- read_csv("data/hrci_arclac_info.csv") %>%
  select(-X1)

vis <- data_vis %>%
  ggplot() +
  geom_point(aes(x = Ycen, y = - Xcen, text = ObsID)) + coord_fixed() +
  labs(x = "", y = "",
       title = "Centers of Mass")

vis %>% ggplotly(source = "centers", tooltip = "text")
```


```{r}
renderPlot({
    eventdata <- event_data("plotly_hover", source = "centers")

    validate(need(!is.null(eventdata), 
                  paste("Hover over the scatter plot chart",
                        "to select which to examine")))
    # Get point number
    data_point <- as.numeric(eventdata$pointNumber)[1] + 1
    ObsID <- data_vis$ObsID[data_point]
    

    file_name <- paste0("images/",ObsID,"_new_image.png")

    my_grob <- file_name %>% lapply(png::readPNG) %>%
      lapply(grid::rasterGrob)
    
  gridExtra::grid.arrange(grobs = my_grob, nrow = 1)    
})
```